### ISSUE TITLE
unfinished games include undrawn letters and letters on players' racks?

### ISSUE THREAD

**Issue by shapr** [benjamincrom/scrabble-challenge#2]
for incomplete games, maybe include letters on the players' rack and letters still undrawn?

**Comment by will2dye4** [comment]
If the objective of the JSON format is to serialize a snapshot of the entire state of a game, then yes, I would agree. On the other hand, if the objective is to facilitate recovery of moves based on scores, I don't think that additional information is needed.

**Comment by shapr** [comment]
ok, works for me.
